### PR TITLE
Microverse collaborative Project 2 completed

### PR DESCRIPTION
**Pull request by M-Alamgir**
We have complete our Microverse collaborative Project 2.

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
Hello @ourandco  and @sempermort 
Well done in getting the project to this point. You have done well but there are still some changes to make.
- [x] You have some linters error, please fix those errors.
- [x] Your readme should be more professional. Update the live link as it doesn't work. Your live link should open up your project. Talk more about the project you have built and what you have done. The screenshot you added to the readme is not loading, you can update it to load properly o remove it entirely.
- [x] You have some commented CSS code. Please remove them and avoid committing commented code in your projects.
- [x] Your navbar doesn't appear like the navbar in the original website in small and medium screen sizes, please fix that. On a medium screen, the TNW logo should disappear from the top 3 article section and that section should behave just like the original behave on a small and medium screen.
- your clone 
Screenshot from 2020-12-02 18-25-33
Screenshot from 2020-12-02 18-25-53
- original
Screenshot from 2020-12-02 18-27-33
Screenshot from 2020-12-02 18-27-53
- [x] The latest news section should align 4 articles per row on a large screen, 3 per row on a medium screen, and 1 per row on a small screen. And each article has a cover image on the left side and a title on the right side of the row on a small screen. Also, check your latest funding section, it should appear and behave exactly as it does on the original website.
- your clone 
Screenshot from 2020-12-02 18-39-36
Screenshot from 2020-12-02 18-39-56
- original
Screenshot from 2020-12-02 18-41-33
Screenshot from 2020-12-02 18-41-53
- [x] Your latest deal section is not responsive as it does not responds as it does in the original website to the different screen sizes. Please refer back to the original website and try to make all sections of the webpage appear, behave and respond to different screen sizes as it does in the original website. Your footer also needs some work.
- [x] Generally, there is a huge horizontal scroll on the webpage and that is because some sections are not responsive and as such, they distort the webpage. As stated before, refer back to the original webpage and make yours as close as you can to the original in terms of appearance and responsiveness.

Request another review when you are done.
Happy coding :+1: 

slack(@ebeagusamuel)

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] the navbar should look like in the desktop version until it reaches 729px, below that it should change to tablet view, and then mobile view. Use the media query inspector to observe the changes on the original website
image

- [x] TheTNW logo in the 3 image section should disappear in tablet view and below
- [x] The website is not fully responsive, the whole content column shrinks on mobile versions
image
image
image

- [x] The latest news and latest deals don't change accordingly to the original website, the 3 columns appear on tablet view to mobile, then on mobile change to one column tablet view goes from 768px to 426px, in a way the project has all the changes, the only differences is the breakpoint when the elements change, they are not using the correct order.


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by M-Alamgir** [comment]
Thanks, Ebeagu Samuel and Julio Añoveros for your review.
I have made your suggested changes.

**Review by layzrd — APPROVED** [review]
###Status: Approved 🙌 🎇
Hi @ourandco and @sempermort, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏  I appreciate your hard work in replicating thenextweb.com.

Now, you can move ahead.

Please don't forget to merge to master. Good luck with the next projects!

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by M-Alamgir** [comment]
Thanks Abdulaziz Redi Ali.

**Pull request merged**
